In [20]:
# example of a normalization
import pandas as pd
from numpy import asarray
from sklearn.preprocessing import StandardScaler, LabelEncoder
# define data
data = pd.read_csv('./iris_dataset.csv')

encoder=LabelEncoder()
data['class']=encoder.fit_transform(data['class'])

# print(data)
# define min max scaler
scaler = StandardScaler()
# # transform data
scaled = scaler.fit_transform(data)
for i in scaled:
    print(i)

[-0.90068117  1.03205722 -1.3412724  -1.31297673 -1.22474487]
[-1.14301691 -0.1249576  -1.3412724  -1.31297673 -1.22474487]
[-1.38535265  0.33784833 -1.39813811 -1.31297673 -1.22474487]
[-1.50652052  0.10644536 -1.2844067  -1.31297673 -1.22474487]
[-1.02184904  1.26346019 -1.3412724  -1.31297673 -1.22474487]
[-0.53717756  1.95766909 -1.17067529 -1.05003079 -1.22474487]
[-1.50652052  0.80065426 -1.3412724  -1.18150376 -1.22474487]
[-1.02184904  0.80065426 -1.2844067  -1.31297673 -1.22474487]
[-1.74885626 -0.35636057 -1.3412724  -1.31297673 -1.22474487]
[-1.14301691  0.10644536 -1.2844067  -1.4444497  -1.22474487]
[-0.53717756  1.49486315 -1.2844067  -1.31297673 -1.22474487]
[-1.26418478  0.80065426 -1.227541   -1.31297673 -1.22474487]
[-1.26418478 -0.1249576  -1.3412724  -1.4444497  -1.22474487]
[-1.87002413 -0.1249576  -1.51186952 -1.4444497  -1.22474487]
[-0.05250608  2.18907205 -1.45500381 -1.31297673 -1.22474487]
[-0.17367395  3.11468391 -1.2844067  -1.05003079 -1.22474487]
[-0.5371