# Pandas library

In [1]:
# Install pandas
!pip install pandas

In [2]:
import pandas as pds

# Series
- Series is a one dimensional labelled array thet can hold/store data

In [3]:
books=["c++","Java","Python","Android","JavaScript"]

In [5]:
sr=pds.Series(books)

In [8]:
sr

0           c++
1          Java
2        Python
3       Android
4    JavaScript
dtype: object

In [11]:
sr[3]

'Android'

In [12]:
type(sr)

pandas.core.series.Series

# DataFrame
- 2 Dimentional Series

In [13]:
import numpy as np
arr=np.random.randint(20,50,(4,4))

In [14]:
arr

array([[46, 43, 24, 36],
       [41, 44, 29, 46],
       [28, 47, 44, 43],
       [27, 49, 43, 42]])

In [26]:
prt=arr[2:4,1:3]
prt

array([[47, 44],
       [49, 43]])

In [29]:
df=pds.DataFrame(data=prt)

In [30]:
df

0   1
0  47  44
1  49  43

In [31]:
prt

array([[47, 44],
       [49, 43]])

In [32]:
df=pds.DataFrame(data=arr)

In [33]:
df

0   1   2   3
0  46  43  24  36
1  41  44  29  46
2  28  47  44  43
3  27  49  43  42

In [39]:
wanted=df[2:][0:]>40

In [40]:
wanted

0     1     2     3
2  False  True  True  True
3  False  True  True  True

In [44]:
df

0   1   2   3
0  46  43  24  36
1  41  44  29  46
2  28  47  44  43
3  27  49  43  42

In [70]:
df[0:][1:]

Names  Ages  Gender  Status
1     41    44      29      46
2     28    47      44      43
3     27    49      43      42

In [69]:
df.columns=["Names","Ages","Gender","Status"]

In [50]:
df

Names  Ages  Gender  Status
0     46    43      24      36
1     41    44      29      46
2     28    47      44      43
3     27    49      43      42

In [66]:
df[0:][0:]

Names  Ages  Gender  Status
0     46    43      24      36
1     41    44      29      46
2     28    47      44      43
3     27    49      43      42

In [71]:
df["Names"]

0    46
1    41
2    28
3    27
Name: Names, dtype: int32

In [72]:
names=["Paul","Yves","Patrick","Viateur"]

In [77]:
df["Ages"]

0    43
1    44
2    47
3    49
Name: Ages, dtype: int32

In [78]:
df.shape

(4, 4)

In [82]:
df.head()

Names  Ages  Gender  Status
0     Paul    43      24      36
1     Yves    44      29      46
2  Patrick    47      44      43
3  Viateur    49      43      42

In [83]:
gender=["Male"]*5
gender

['Male', 'Male', 'Male', 'Male', 'Male']

In [84]:
gender=["Male"]*4

In [85]:
gender

['Male', 'Male', 'Male', 'Male']

In [89]:
df

Names  Ages Gender  Status
0     Paul    43   Male      36
1     Yves    44   Male      46
2  Patrick    47   Male      43
3  Viateur    49   Male      42

In [90]:
status=["Married","Married","Single","Married"]

In [92]:
df

Names  Ages Gender   Status
0     Paul    43   Male  Married
1     Yves    44   Male  Married
2  Patrick    47   Male   Single
3  Viateur    49   Male  Married

In [96]:
df.head(1)

Names  Ages Gender   Status
0  Paul    43   Male  Married

In [97]:
df.tail(1)

Names  Ages Gender   Status
3  Viateur    49   Male  Married

In [102]:
cols=["Names","Status"]
df[["Ages","Status","Names"]]

Ages   Status    Names
0    43  Married     Paul
1    44  Married     Yves
2    47   Single  Patrick
3    49  Married  Viateur

In [103]:
df["LastName"]=["Nishimirwe","Himbaza","Ishimwe","Gombaniro"]

In [104]:
df

Names  Ages Gender   Status    LastName
0     Paul    43   Male  Married  Nishimirwe
1     Yves    44   Male  Married     Himbaza
2  Patrick    47   Male   Single     Ishimwe
3  Viateur    49   Male  Married   Gombaniro

In [105]:
df["Gender2"]=["Fem"]*4

In [107]:
df

Names  Ages Gender   Status    LastName Gender2
0     Paul    43   Male  Married  Nishimirwe     Fem
1     Yves    44   Male  Married     Himbaza     Fem
2  Patrick    47   Male   Single     Ishimwe     Fem
3  Viateur    49   Male  Married   Gombaniro     Fem

In [108]:
df.drop(columns="Gender2")

Names  Ages Gender   Status    LastName
0     Paul    43   Male  Married  Nishimirwe
1     Yves    44   Male  Married     Himbaza
2  Patrick    47   Male   Single     Ishimwe
3  Viateur    49   Male  Married   Gombaniro

0   1     2        3           4
0     Paul  43  Male  Married  Nishimirwe
1     Yves  44  Male  Married     Himbaza
2  Viateur  49  Male  Married   Gombaniro

In [110]:
df=df.drop(columns=["Gender2"])

In [111]:
df

Names  Ages Gender   Status    LastName
0     Paul    43   Male  Married  Nishimirwe
1     Yves    44   Male  Married     Himbaza
2  Patrick    47   Male   Single     Ishimwe
3  Viateur    49   Male  Married   Gombaniro

In [113]:
#Extract rows of DataFrame
df.iloc[2]

Names       Patrick
Ages             47
Gender         Male
Status       Single
LastName    Ishimwe
Name: 2, dtype: object

In [130]:
df.iloc[1:3,0:]

Names  Ages Gender   Status LastName
1     Yves    44   Male  Married  Himbaza
2  Patrick    47   Male   Single  Ishimwe

In [134]:
mask=df["Ages"]>45
np.sum(mask)

2

In [135]:
df[mask]

Names  Ages Gender   Status   LastName
2  Patrick    47   Male   Single    Ishimwe
3  Viateur    49   Male  Married  Gombaniro

In [141]:
df[df["Status"]=="Single"]

Names  Ages Gender  Status LastName
2  Patrick    47   Male  Single  Ishimwe

In [166]:
df

0   1     2        3           4
0     Paul  43  Male  Married  Nishimirwe
1     Yves  44  Male  Married     Himbaza
2  Viateur  49  Male  Married   Gombaniro

In [168]:
df.columns=["Names","Ages","Gender","Status","LastName"]

In [169]:
df

Names Ages Gender   Status    LastName
0     Paul   43   Male  Married  Nishimirwe
1     Yves   44   Male  Married     Himbaza
2  Viateur   49   Male  Married   Gombaniro

# Iris DataSet

In [174]:
iris=pds.read_csv("./iris.csv")

In [175]:
type(iris)

pandas.core.frame.DataFrame

In [176]:
iris.shape

(150, 5)

In [179]:
iris.tail(4)

sepal_length  sepal_width  petal_length  petal_width    species
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [183]:
iris[iris["species"]=="setosa"]

sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.1  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.1           1.5          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

In [185]:
iris.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [186]:
iris.info

<bound method DataFrame.info of      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>