In [5]:
import numpy as np

In [6]:
li=[]

In [7]:
li.append(90)

In [8]:
li

[90]

In [10]:
arr=np.array(li)

In [11]:
type(arr)

numpy.ndarray

In [12]:
arr2=np.array(
[[1,2,3],[4,5,6],[7,8,9]])

In [13]:
type(arr2)

numpy.ndarray

In [14]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr2[1:][:]

array([[4, 5, 6],
       [7, 8, 9]])

In [16]:
sum(arr2)

array([12, 15, 18])

In [17]:
li=[3,4,5]
arr=li*2

In [18]:
arr

[3, 4, 5, 3, 4, 5]

In [25]:
%timeit [i**2 for i in li]

720 ns ± 22.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [27]:
arr=np.array(li)

In [28]:
%timeit [i**2 for i in arr]

1.63 µs ± 23.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [22]:
def greater(x):
    return x>=10

In [29]:
g=[greater(i) for i in arr]

In [30]:
g

[False, False, False]

In [32]:
arr.ndim

1

In [33]:
arr.shape

(3,)

In [34]:
arr

array([3, 4, 5])

In [36]:
for i in arr:
    if i>=5:
        print(i)

5


In [40]:
def even(x):
    if x%2==0:
        return x

evens=[even(i) for i in arr]

In [41]:
print(evens)

[None, 4, None]


In [42]:
evens.remove(None)

In [43]:
evens

[4, None]

In [44]:
evens.pop()

In [45]:
evens

[4]

In [46]:
zeros=[0]*4

In [48]:
zeros
zz=np.zeros(5)

In [49]:
zz.shape

(5,)

In [50]:
len(zz)

5

In [52]:
zz

array([0., 0., 0., 0., 0.])

In [53]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 

In [54]:
student

dtype([('name', 'S20'), ('age', 'i1'), ('marks', '<f4')])

In [57]:
people=np.array([("Paul",24),("Josiane",23),("Yves",24)])

In [58]:
for i in people:
    print(f"{i[0]} has {i[-1]} years")

Paul has 24 years
Josiane has 23 years
Yves has 24 years


In [66]:
new_arr=np.array([[1, 5,19, 8],
                 [11, 5,12, 1],
                 [6, 8,  2, 9],
                 [15, 3, 9, 15],
                 [2, 4, 14, 6]])

In [67]:
print(new_arr[2,1])

8


In [68]:
print(new_arr[2:4,1:3])

[[8 2]
 [3 9]]


In [69]:
print(new_arr[1:2,1:])

[[ 5 12  1]]


In [72]:
print(new_arr[:,2:3])

[[19]
 [12]
 [ 2]
 [ 9]
 [14]]


In [73]:
new_arr

array([[ 1,  5, 19,  8],
       [11,  5, 12,  1],
       [ 6,  8,  2,  9],
       [15,  3,  9, 15],
       [ 2,  4, 14,  6]])

In [74]:
new_arr == 8

array([[False, False, False,  True],
       [False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [76]:
mask=new_arr==8

In [79]:
np.sum(mask)

2

mask

In [80]:
mask

array([[False, False, False,  True],
       [False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [81]:
new_arr[:,:]=2

In [82]:
new_arr

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [95]:
new_arr=np.array([4,10,12,16,90,180,270])

In [96]:
sins=(np.log(new_arr))

In [94]:
sins

array([1.38629436, 1.60943791, 2.48490665, 2.77258872, 4.49980967,
       5.19295685, 5.59842196])

In [103]:
A=np.array([[20,10],
           [50,70]])

B=A/10

In [104]:
B

array([[2., 1.],
       [5., 7.]])

In [105]:
C=A+B

In [107]:
C

array([[22., 11.],
       [55., 77.]])

In [108]:
D=A*B

In [109]:
D

array([[ 40.,  10.],
       [250., 490.]])

In [110]:
print(D[:,1])

[ 10. 490.]


In [112]:
E=np.dot(A,B)

In [113]:
E

array([[ 90.,  90.],
       [450., 540.]])

In [114]:
A

array([[20, 10],
       [50, 70]])

In [115]:
B

array([[2., 1.],
       [5., 7.]])

In [116]:
np.max(A)

70

In [117]:
np.sum(A)

150

In [118]:
A

array([[20, 10],
       [50, 70]])

In [119]:
np.std(A)

23.84848003542364

In [121]:
np.mean(A)

37.5

In [122]:
np.sum(A)/len(A)

75.0

In [123]:
len(A)

2

In [124]:
a=A.shape

In [125]:
a

(2, 2)

In [126]:
np.sum(A, axis=0)

array([70, 80])

In [127]:
A

array([[20, 10],
       [50, 70]])

In [128]:
np.sum(A, axis=1)

array([ 30, 120])

In [129]:
A.T

array([[20, 50],
       [10, 70]])

In [130]:
A

array([[20, 10],
       [50, 70]])

#### Assignment

In [133]:
arr=np.arange(1,16+1)

In [134]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [135]:
for i in arr:
    print(f"{i} ",end='')

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 

In [143]:
def odd(x):
    return x%2!=0
    

In [144]:
res=filter(odd,arr)

In [145]:
for i in res:
    print(i)

1
3
5
7
9
11
13
15
