In [1]:
!pip install numpy

In [2]:
import numpy as npy

In [3]:
lst=[1,2,3,4,5,6,7,8,9,10,11]

In [4]:
%timeit [i**2 for i in lst]

6.17 µs ± 48.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Numpy Array
- Has many advanced operation that usual python list

In [5]:
arr=npy.array(lst)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
%timeit arr**2

1.56 µs ± 26.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [12]:
arr1=arr**2
for i in arr1:
    print(f"{i} : ",end='')

1 : 4 : 9 : 16 : 25 : 36 : 49 : 64 : 81 : 100 : 121 : 

# Creating numpy arrays
- numpy.array(), We can pass list in paranthesis
- numpy.arange(), we can pass a list in there

In [13]:
li=[34,56,87]

In [24]:
arr=npy.array(li)
print(arr+3)

[37 59 90]


In [15]:
type(arr)

numpy.ndarray

In [16]:
arr.ndim

1

In [17]:
arr.shape

(3,)

In [20]:
a=len(arr)
a

3

# Using arange to create a numpy array

In [25]:
arr=npy.arange(1,10)

In [26]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
def isEven(i):
    return i%2==0

In [36]:
myList=list(filter(isEven,arr))
myList=npy.array(myList)
print(myList,type(myList))

[2 4 6 8] <class 'numpy.ndarray'>


# 2D Arrays

In [37]:
list_2d=[ [1,2,3],
          [4,5,6],
          [7,8,9]]
list_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [38]:
arr_2d=npy.array(list_2d)

In [39]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr_2d.ndim

2

In [41]:
arr_2d.shape

(3, 3)

In [43]:
for i in range(len(arr_2d)):
    for j in range(len(arr_2d[0])):
        print(f"{arr_2d[i][j]} : ",end='')
    print()

1 : 2 : 3 : 
4 : 5 : 6 : 
7 : 8 : 9 : 


In [44]:
len(arr_2d)

3

In [45]:
len(list_2d)

3

# Python special arrays with numpy Library
- zeros()
- ones()
- diag()
- identity()

# zeros()

In [60]:
npy.diag(npy.arange(1,6))


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [77]:
go=True
while go:
    n=int(input("Guess a number: "))
    r=npy.random.randint(1,20)
    if(n==r):
        print(f"Won with {n}")
        go=False
    else:
        print(f"You missed. You entered {n} while a number is {r}. Another chance: ")
        

Guess a number: 14
You missed. You entered 14 while a number is 7. Another chance: 
Guess a number: 3
You missed. You entered 3 while a number is 16. Another chance: 
Guess a number: 18
You missed. You entered 18 while a number is 17. Another chance: 
Guess a number: 11
You missed. You entered 11 while a number is 13. Another chance: 
Guess a number: 16
You missed. You entered 16 while a number is 7. Another chance: 
Guess a number: 4
You missed. You entered 4 while a number is 15. Another chance: 
Guess a number: 12
You missed. You entered 12 while a number is 15. Another chance: 
Guess a number: 18
You missed. You entered 18 while a number is 15. Another chance: 
Guess a number: 17
You missed. You entered 17 while a number is 12. Another chance: 
Guess a number: 17
You missed. You entered 17 while a number is 3. Another chance: 
Guess a number: 9
You missed. You entered 9 while a number is 17. Another chance: 
Guess a number: 13
You missed. You entered 13 while a number is 2. Another

In [100]:
arr_2d=npy.array([[1,2,3,4,5],
        [5,6,7,8,2],
        [5,2,7,2,8],
        [6,9,6,8,2]])

In [101]:
arr_2d

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 2],
       [5, 2, 7, 2, 8],
       [6, 9, 6, 8, 2]])

In [104]:
derived=arr_2d[2:4,2:5]
derived

array([[7, 2, 8],
       [6, 8, 2]])